/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testdatabase;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class FormKoneksi extends javax.swing.JFrame {
private static Connection koneksi;
private DefaultTableModel model;
    /**
     * Creates new form FormKoneksi
     */
    
     public FormKoneksi() {
         initComponents();
         model=new DefaultTableModel();
         this.jTable1.setModel(model);
         model.addColumn("ID");
         model.addColumn("Nama");
         model.addColumn("Alamat");
         model.addColumn("Telepon");
         ambil_data_tabel();

         }
     private static Connection buka_koneksi() {
            if (koneksi==null) {
                try {
                String url="jdbc:mysql://localhost:3306/belajar";
                String user="root";
                String password="";

                DriverManager.registerDriver(new com.mysql.jdbc.Driver());
                koneksi=DriverManager.getConnection(url,user,password);
                    }catch (SQLException t) {
                    System.out.println("Error membuat koneksi");
                    }
            }
            return koneksi;
        }
     private void ambil_data_tabel()
        {
         model.getDataVector().removeAllElements();
         model.fireTableDataChanged();
         try {
                Connection c=buka_koneksi();
                Statement s= c.createStatement();
                String sql="Select * from anggota";
                ResultSet r=s.executeQuery(sql);

                while (r.next()) {
                    Object[] o=new Object[4];
                    o[0]=r.getString("id");
                    o[1]=r.getString("nama");
                    o[2]=r.getString("alamat");
                    o[3]=r.getString("telp");
                    model.addRow(o);
                }
        
                r.close();
                s.close();
                ambil_tabel_klik();
           }catch(SQLException e) {
            System.out.println("Terjadi kesalahan "+e.getMessage());
             }
        }
     private void ambil_tabel_klik()
            {
                int i=this.jTable1.getSelectedRow();
                if(i==-1)
                {
                return;
                }
                String kode=(String) model.getValueAt(i, 0);
                this.lblKode.setText(kode);
                String nama=(String) model.getValueAt(i, 0);
                this.TxtNama.setText(nama);
                String alamat=(String) model.getValueAt(i, 1);
                this.TxtAlamat.setText(alamat);
                String telp=(String) model.getValueAt(i, 2);
                this.TxtTelepon.setText(telp);
            }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cmbEdit = new javax.swing.JButton();
        cmbAdd = new javax.swing.JButton();
        cmbDelete = new javax.swing.JButton();
        cmbRefresh = new javax.swing.JButton();
        lblKode = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TxtNama = new javax.swing.JTextField();
        TxtAlamat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtTelepon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        cmbEdit.setText("edit");
        cmbEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEditActionPerformed(evt);
            }
        });

        cmbAdd.setText("add");
        cmbAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAddActionPerformed(evt);
            }
        });

        cmbDelete.setText("delete");
        cmbDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDeleteActionPerformed(evt);
            }
        });

        cmbRefresh.setText("refresh");
        cmbRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRefreshActionPerformed(evt);
            }
        });

        lblKode.setText("0");

        jLabel1.setText("Nama");

        jLabel2.setText("Alamat");

        jLabel3.setText("Telepon");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(322, Short.MAX_VALUE)
                .addComponent(cmbEdit)
                .addGap(100, 100, 100))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblKode)
                                            .addComponent(TxtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(25, 25, 25)
                                    .addComponent(TxtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(22, 22, 22)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbDelete)
                                .addComponent(cmbRefresh)
                                .addComponent(cmbAdd))
                            .addGap(0, 79, Short.MAX_VALUE)))
                    .addGap(4, 4, 4)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(cmbEdit)
                .addContainerGap(357, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(TxtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbAdd))
                    .addGap(2, 2, 2)
                    .addComponent(lblKode)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(TxtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(36, 36, 36)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(TxtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbDelete))
                    .addGap(36, 36, 36)
                    .addComponent(cmbRefresh)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(37, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAddActionPerformed
        // TODO add your handling code here:
        Connection c=buka_koneksi();
        if("Add".equals(this.cmbAdd.getText()))
        {
            this.cmbAdd.setText("Save");
            this.cmbEdit.setText("Cancel");
            this.cmbDelete.enable(false);
            this.cmbRefresh.enable(false);
            this.lblKode.setText("0");
            this.TxtNama.setText("");
            this.TxtAlamat.setText("");
            this.TxtTelepon.setText("");

        }else if("Save".equals(this.cmbAdd.getText()))
        {

        String sqlkode="Insert into anggota (`nama`,`alamat`,`telp`) "
               + "values ('"+this.TxtNama.getText()+"',"
               + "'"+this.TxtAlamat.getText()+"',"
               + "'"+this.TxtTelepon.getText()+"')";
        try {
        PreparedStatement p2=(PreparedStatement)
        c.prepareStatement(sqlkode);
        p2.executeUpdate();
        p2.close();
        } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan"+ex.getMessage());
        }
        this.cmbAdd.setText("Add");
        this.cmbEdit.setText("Edit");
        this.cmbDelete.enable(true);
        this.cmbRefresh.enable(true);
        }else if("Update".equals(this.cmbAdd.getText()))
        {
        String sqlkode="Update anggota SET`nama`='"+this.TxtNama.getText()+"',"
               + "`alamat`='"+this.TxtAlamat.getText()+"',"
               + "`telp`='"+this.TxtTelepon.getText()+"' "
               + "Where ID='"+this.lblKode.getText()+"'";
        try {
        PreparedStatement p2=(PreparedStatement)
        c.prepareStatement(sqlkode);
        p2.executeUpdate();
        p2.close();
        } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan"+ex.getMessage());
        }
            this.cmbAdd.setText("Add");
            this.cmbEdit.setText("Edit");
            this.cmbDelete.enable(true);
            this.cmbRefresh.enable(true);
        }
    }//GEN-LAST:event_cmbAddActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        this.ambil_tabel_klik();
    }//GEN-LAST:event_jTable1MouseClicked

    private void cmbEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEditActionPerformed
        // TODO add your handling code here:
      if("Edit".equals(this.cmbEdit.getText()))
         {
            this.cmbAdd.setText("Update");
            this.cmbEdit.setText("Cancel");
            this.cmbDelete.enable(false);
            this.cmbRefresh.enable(false);
            }else if("Cancel".equals(this.cmbEdit.getText()))
           {
            this.cmbAdd.setText("Add");
            this.cmbEdit.setText("Edit");
            this.cmbDelete.enable(true);
            this.cmbRefresh.enable(true);
         }
    }//GEN-LAST:event_cmbEditActionPerformed

    private void cmbDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDeleteActionPerformed
        // TODO add your handling code here:
        Connection c=buka_koneksi();
        String sqlkode="Delete from anggota "
        + "Where ID='"+this.lblKode.getText()+"'";
        try {
        PreparedStatement p2=(PreparedStatement)
       c.prepareStatement(sqlkode);
        p2.executeUpdate();
        p2.close();
        } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan"+ex.getMessage());
        }
    }//GEN-LAST:event_cmbDeleteActionPerformed

    private void cmbRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRefreshActionPerformed
        // TODO add your handling code here:
        ambil_data_tabel();
    }//GEN-LAST:event_cmbRefreshActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKoneksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKoneksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKoneksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKoneksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKoneksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtAlamat;
    private javax.swing.JTextField TxtNama;
    private javax.swing.JTextField TxtTelepon;
    private javax.swing.JButton cmbAdd;
    private javax.swing.JButton cmbDelete;
    private javax.swing.JButton cmbEdit;
    private javax.swing.JButton cmbRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblKode;
    // End of variables declaration//GEN-END:variables
}
